#Below configuration is automatically done by spring for H2-databse. But If we are using any other databse like Myql then we have to configure all below properties as given
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    password: ''
#    url: jdbc:h2:mem:testdb
#    username: sa

spring:
  h2:
    console:
      enabled: true
      path: /h2   #Default is /h2-console
      settings:
        trace: false #Default is also false
        web-allow-others: false #Default is also false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl